/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagement;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Rajani
 */
public class AddBooks extends javax.swing.JFrame {

    /**
     * Creates new form AddBooks
     */
    public AddBooks() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddBookspage = new javax.swing.JLabel();
        Backadd = new javax.swing.JLabel();
        bookid = new javax.swing.JTextField();
        namee = new javax.swing.JTextField();
        publisherr = new javax.swing.JTextField();
        pricee = new javax.swing.JTextField();
        publisheryearr = new javax.swing.JTextField();
        SaveAdd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddBookspage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagement/add book.jpg"))); // NOI18N
        getContentPane().add(AddBookspage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Backadd.setText("jLabel1");
        Backadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackaddMouseClicked(evt);
            }
        });
        getContentPane().add(Backadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 405, 60, 30));

        bookid.setBackground(new java.awt.Color(193, 193, 224));
        bookid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookidActionPerformed(evt);
            }
        });
        getContentPane().add(bookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 110, 350, -1));

        namee.setBackground(new java.awt.Color(193, 193, 224));
        getContentPane().add(namee, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 170, 350, -1));

        publisherr.setBackground(new java.awt.Color(193, 193, 224));
        getContentPane().add(publisherr, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 230, 350, -1));

        pricee.setBackground(new java.awt.Color(193, 193, 224));
        getContentPane().add(pricee, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 290, 350, -1));

        publisheryearr.setBackground(new java.awt.Color(193, 193, 224));
        getContentPane().add(publisheryearr, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 350, 350, -1));

        SaveAdd.setText("jLabel1");
        SaveAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveAddMouseClicked(evt);
            }
        });
        getContentPane().add(SaveAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 405, 70, 30));

        setSize(new java.awt.Dimension(900, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for(double i=0.0; i<=1.0; i=0.1+i)
        {
         String val = i+"";
         float f =Float.valueOf(val);
         this.setOpacity(f);
         try
         {
             Thread.sleep(50);
         }
         catch(InterruptedException e)
                 {
                     
                 }
        }
    }//GEN-LAST:event_formWindowOpened

    private void BackaddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackaddMouseClicked
        new FrontPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackaddMouseClicked

    private void SaveAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveAddMouseClicked
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/librarymanagement", "root", "");
            Statement stmt = (Statement) con.createStatement();
            String query = "insert into addbooks (BookID, Name, Publisher, price,publisheryear) values ('"+bookid.getText()+"', '"+namee.getText()+"', '"+publisherr.getText()+"', '"+pricee.getText()+"', '"+publisheryearr.getText()+"')";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Data successfullly inserted");
                       
        }
        catch(HeadlessException | ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error"+ ex);
        }
    }//GEN-LAST:event_SaveAddMouseClicked

    private void bookidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddBookspage;
    private javax.swing.JLabel Backadd;
    private javax.swing.JLabel SaveAdd;
    private javax.swing.JTextField bookid;
    private javax.swing.JTextField namee;
    private javax.swing.JTextField pricee;
    private javax.swing.JTextField publisherr;
    private javax.swing.JTextField publisheryearr;
    // End of variables declaration//GEN-END:variables

}
