/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagement;

import java.awt.Color;

/**
 *
 * @author Rajani
 */
public class FrontPage extends javax.swing.JFrame {

    /**
     * Creates new form FrontPage
     */
    public FrontPage() {
        initComponents();
        setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AddBooksbutton = new javax.swing.JLabel();
        IssueBooksbutton = new javax.swing.JLabel();
        ReturnBooksbutton = new javax.swing.JLabel();
        Viewissuebutton = new javax.swing.JLabel();
        viewbooksbutton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("label1"); // NOI18N
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagement/front page final.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        AddBooksbutton.setText("jLabel2");
        AddBooksbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBooksbuttonMouseClicked(evt);
            }
        });
        getContentPane().add(AddBooksbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 85, 150, 50));

        IssueBooksbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IssueBooksbuttonMouseClicked(evt);
            }
        });
        getContentPane().add(IssueBooksbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 265, 130, 40));

        ReturnBooksbutton.setText("jLabel2");
        ReturnBooksbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReturnBooksbuttonMouseClicked(evt);
            }
        });
        getContentPane().add(ReturnBooksbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 435, 160, 40));

        Viewissuebutton.setText("jLabel2");
        Viewissuebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewissuebuttonMouseClicked(evt);
            }
        });
        getContentPane().add(Viewissuebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 345, 170, 40));

        viewbooksbutton.setText("jLabel2");
        viewbooksbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewbooksbuttonMouseClicked(evt);
            }
        });
        getContentPane().add(viewbooksbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 175, 160, 40));

        setSize(new java.awt.Dimension(900, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for(double i=0.0; i<=1.0; i=0.1+i)
        {
         String val = i+"";
         float f =Float.valueOf(val);
         this.setOpacity(f);
         try
         {
             Thread.sleep(10);
         }
         catch(InterruptedException e)
                 {
                     
                 }
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void AddBooksbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBooksbuttonMouseClicked
        new AddBooks().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddBooksbuttonMouseClicked

    private void IssueBooksbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IssueBooksbuttonMouseClicked
        new IssueBooks().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IssueBooksbuttonMouseClicked

    private void ReturnBooksbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnBooksbuttonMouseClicked
         new ReturnBooks().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReturnBooksbuttonMouseClicked

    private void ViewissuebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewissuebuttonMouseClicked
        
    }//GEN-LAST:event_ViewissuebuttonMouseClicked

    private void viewbooksbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewbooksbuttonMouseClicked
        new Viewbooks().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewbooksbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrontPage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddBooksbutton;
    private javax.swing.JLabel IssueBooksbutton;
    private javax.swing.JLabel ReturnBooksbutton;
    private javax.swing.JLabel Viewissuebutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel viewbooksbutton;
    // End of variables declaration//GEN-END:variables
}
