/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagement;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Rajani
 */
public class ReturnBooks extends javax.swing.JFrame {
   

    /**
     * Creates new form ReturnBooks
     */
    public ReturnBooks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Backreturn = new javax.swing.JLabel();
        SearchReturn = new javax.swing.JLabel();
        bookidr = new javax.swing.JTextField();
        studentidr = new javax.swing.JTextField();
        issuedater = new javax.swing.JTextField();
        duedater = new javax.swing.JTextField();
        returnn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagement/returnsearch.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        Backreturn.setText("jLabel2");
        Backreturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackreturnMouseClicked(evt);
            }
        });
        getContentPane().add(Backreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 385, 80, 30));

        SearchReturn.setText("jLabel2");
        SearchReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchReturnMouseClicked(evt);
            }
        });
        getContentPane().add(SearchReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 125, 50, 40));

        bookidr.setBackground(new java.awt.Color(193, 193, 224));
        getContentPane().add(bookidr, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 130, 320, 20));

        studentidr.setBackground(new java.awt.Color(193, 193, 224));
        getContentPane().add(studentidr, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 200, 370, -1));

        issuedater.setBackground(new java.awt.Color(193, 193, 224));
        getContentPane().add(issuedater, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 260, 370, -1));

        duedater.setBackground(new java.awt.Color(193, 193, 224));
        getContentPane().add(duedater, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 320, 370, -1));

        returnn.setText("jLabel2");
        returnn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnnMouseClicked(evt);
            }
        });
        getContentPane().add(returnn, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 380, 80, 40));

        setSize(new java.awt.Dimension(900, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackreturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackreturnMouseClicked
        new FrontPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackreturnMouseClicked

    private void SearchReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchReturnMouseClicked

         try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/librarymanagement", "root", "");
            String query = "select * from issuebooks where BookID ='"+bookidr.getText()+"'";
            PreparedStatement statement = con.prepareStatement(query);
            
            ResultSet set = statement.executeQuery();
            while(set.next()){
            studentidr.setText(set.getString("StudentID"));
            issuedater.setText(set.getString("IssueDate"));
            duedater.setText(set.getString("DueDate"));
            
            }
         }
         catch(ClassNotFoundException | SQLException ex){
            JOptionPane.showMessageDialog(null, "Error"+ ex);
        }
    }//GEN-LAST:event_SearchReturnMouseClicked

    private void returnnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnnMouseClicked
        try {
            Class.forName("com.mysql.jdbc.Driver");           
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/librarymanagement", "root", "");
            Statement stmt = (Statement) con.createStatement();
            String query = "delete from issuebooks where BookID = '"+bookidr.getText()+"'  ";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Data deleted successfully");
                       
        }catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "Error"+ ex);
        }
    }//GEN-LAST:event_returnnMouseClicked

        
    
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ReturnBooks().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backreturn;
    private javax.swing.JLabel SearchReturn;
    private javax.swing.JTextField bookidr;
    private javax.swing.JTextField duedater;
    private javax.swing.JTextField issuedater;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel returnn;
    private javax.swing.JTextField studentidr;
    // End of variables declaration//GEN-END:variables
}
