/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagement;

import com.mysql.jdbc.Connection;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Rajani
 */
public class ViewissueBooks extends javax.swing.JFrame {

    /**
     * Creates new form ViewissueBooks
     */
    StringBuffer result=new StringBuffer();
    public ViewissueBooks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        homepage = new javax.swing.JLabel();
        searchissuebooks = new javax.swing.JLabel();
        textforsearch = new javax.swing.JTextField();
        textareaa = new javax.swing.JScrollPane();
        textshown = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        refreshb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagement/refresh1.jpg"))); // NOI18N
        refreshb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshbMouseClicked(evt);
            }
        });
        getContentPane().add(refreshb, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 40, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagement/Issue books home.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        homepage.setText("jLabel2");
        homepage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homepageMouseClicked(evt);
            }
        });
        getContentPane().add(homepage, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 95, 40, 40));

        searchissuebooks.setText("jLabel2");
        searchissuebooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchissuebooksMouseClicked(evt);
            }
        });
        getContentPane().add(searchissuebooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 95, 40, 40));

        textforsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textforsearchActionPerformed(evt);
            }
        });
        getContentPane().add(textforsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 99, 340, 30));

        textareaa.setBackground(new java.awt.Color(204, 204, 204));

        textshown.setBackground(new java.awt.Color(255, 255, 255));
        textshown.setColumns(20);
        textshown.setRows(5);
        textareaa.setViewportView(textshown);

        getContentPane().add(textareaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 420, 310));

        setSize(new java.awt.Dimension(900, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchissuebooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchissuebooksMouseClicked
          if("".equals(textforsearch.getText()))
        {
            JOptionPane.showMessageDialog(null, "Please enter the id number to search");
            return;
        }
        result=new StringBuffer("");
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/librarymanagement", "root", "");
            String query = "select * from issuebooks where BookID ='"+textforsearch.getText()+"';";
            PreparedStatement statement = con.prepareStatement(query);
            ResultSet set = statement.executeQuery();
            while(set.next()){
                result.append("Book ID: ").append(set.getString("BookID")).append('\n');
                result.append("Student ID: ").append(set.getString("StudentID")).append('\n');
                result.append("Issue Date: ").append(set.getString("IssueDate")).append('\n');
                result.append("Due Date: ").append(set.getString("DueDate")).append('\n');
                result.append("\n\n");
            }
            if("".equals(result.toString()))
            {
                JOptionPane.showMessageDialog(null, "There is no record with that id. Please enter valid id.");
            }
            textshown.setText(result.toString( ));
            result=new StringBuffer("");
        }
        catch(HeadlessException | ClassNotFoundException | SQLException ex){
            JOptionPane.showMessageDialog(null, "Error"+ ex);
        }
    }//GEN-LAST:event_searchissuebooksMouseClicked

    private void homepageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepageMouseClicked
        new FrontPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homepageMouseClicked

    private void textforsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textforsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textforsearchActionPerformed

    private void refreshbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshbMouseClicked
        result=new StringBuffer("");
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/librarymanagement", "root", "");
            String query = "select * from issuebooks;";
            PreparedStatement statement = con.prepareStatement(query);
            ResultSet set = statement.executeQuery();
            if(set!=null)
            {
                while(set.next()){
                    result.append("Book ID: ").append(set.getString("BookID")).append('\n');
                    result.append("Student ID: ").append(set.getString("StudentID")).append('\n');
                    result.append("Issue Date: ").append(set.getString("IssueDate")).append('\n');
                    result.append("Due Date: ").append(set.getString("DueDate")).append('\n');
                    result.append("\n\n");
                }
                textshown.setText(result.toString());
                result=new StringBuffer("");
            }
            else
            {
                textshown.setText("No Record!");
                result=new StringBuffer("");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error"+ ex);
        }
    }//GEN-LAST:event_refreshbMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewissueBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewissueBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewissueBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewissueBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewissueBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel homepage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel refreshb;
    private javax.swing.JLabel searchissuebooks;
    private javax.swing.JScrollPane textareaa;
    private javax.swing.JTextField textforsearch;
    private javax.swing.JTextArea textshown;
    // End of variables declaration//GEN-END:variables
}
