/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagement;

import com.mysql.jdbc.Connection;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Rajani
 */
public class Viewbooks extends javax.swing.JFrame {

    /**
     * Creates new form Viewbooks
     */
    StringBuffer result=new StringBuffer();
    public Viewbooks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshh = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        gohome = new javax.swing.JLabel();
        textareea = new javax.swing.JScrollPane();
        textshownn = new javax.swing.JTextArea();
        searchh = new javax.swing.JLabel();
        textfohsearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        refreshh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagement/refresh1.jpg"))); // NOI18N
        refreshh.setText("jLabel1");
        refreshh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshhMouseClicked(evt);
            }
        });
        getContentPane().add(refreshh, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 40, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagement/Issue books home.jpg"))); // NOI18N
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        gohome.setText("jLabel1");
        gohome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gohomeMouseClicked(evt);
            }
        });
        getContentPane().add(gohome, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 95, 50, 40));

        textshownn.setColumns(20);
        textshownn.setRows(5);
        textareea.setViewportView(textshownn);

        getContentPane().add(textareea, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 410, 310));

        searchh.setText("jLabel1");
        searchh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchhMouseClicked(evt);
            }
        });
        getContentPane().add(searchh, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 95, 40, 40));

        textfohsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfohsearchActionPerformed(evt);
            }
        });
        getContentPane().add(textfohsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 350, 30));

        setSize(new java.awt.Dimension(900, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gohomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gohomeMouseClicked
       new FrontPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gohomeMouseClicked

    private void textfohsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfohsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfohsearchActionPerformed

    private void searchhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchhMouseClicked
         if("".equals(textfohsearch.getText()))
        {
            JOptionPane.showMessageDialog(null, "Please enter the id number to search");
            return;
        }
        result=new StringBuffer("");
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/librarymanagement", "root", "");
            String query = "select * from addbooks where BookID ='"+textfohsearch.getText()+"';";
            PreparedStatement statement = con.prepareStatement(query);
            ResultSet set = statement.executeQuery();
            while(set.next()){
                result.append("Book ID : ").append(set.getString("BookID")).append('\n');
                result.append("Name : ").append(set.getString("Name")).append('\n');
                result.append("Publisher : ").append(set.getString("Publisher")).append('\n');
                result.append("Price : ").append(set.getString("price")).append('\n');
                result.append("Publisher Year : ").append(set.getString("publisheryear")).append('\n');
                result.append("\n\n");
            }
            if("".equals(result.toString()))
            {
                JOptionPane.showMessageDialog(null, "There is no record with that id. Please enter valid id.");
            }
            textshownn.setText(result.toString( ));
            result=new StringBuffer("");
        }
        catch(HeadlessException | ClassNotFoundException | SQLException ex){
            JOptionPane.showMessageDialog(null, "Error"+ ex);
        }
    }//GEN-LAST:event_searchhMouseClicked

    private void refreshhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshhMouseClicked
        result=new StringBuffer("");
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/librarymanagement", "root", "");
            String query = "select * from addbooks;";
            PreparedStatement statement = con.prepareStatement(query);
            ResultSet set = statement.executeQuery();
            if(set!=null)
            {
                while(set.next()){
                    result.append("Book ID : ").append(set.getString("BookID")).append('\n');
                    result.append("Name : ").append(set.getString("Name")).append('\n');
                    result.append("Publisher : ").append(set.getString("Publisher")).append('\n');
                    result.append("Price : ").append(set.getString("price")).append('\n');
                    result.append("Publisher Year : ").append(set.getString("publisheryear")).append('\n');
                    result.append("\n\n");
                }
                textshownn.setText(result.toString());
                result=new StringBuffer("");
            }
            else
            {
                textshownn.setText("No Record!");
                result=new StringBuffer("");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error"+ ex);
        }
    }//GEN-LAST:event_refreshhMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viewbooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viewbooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viewbooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viewbooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Viewbooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gohome;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel refreshh;
    private javax.swing.JLabel searchh;
    private javax.swing.JScrollPane textareea;
    private javax.swing.JTextField textfohsearch;
    private javax.swing.JTextArea textshownn;
    // End of variables declaration//GEN-END:variables
}
